### ISSUE TITLE
Allow to run command outside actions

### ISSUE THREAD

**Issue by mildronize** [thaitype/actions-node#2]
```yml
- uses: thaitype/actions-node/pnpm@v1
  id: run-node
  with: 
    repository: thaitype/demo-node
    token: ${{ secrets.GITHUB_TOKEN }}
    node-version: "20"
    pnpm-version: "8"

- run: node index.js
  working-directory: ${{ steps.run-node.outputs.working-directory }}
```
